import { WorkItem, SiteInfo, SidebarMenu } from './types';

export const INITIAL_SITE_INFO: SiteInfo = {
  heroHeadline: "브랜드 {톤} 위에서,\n{소비자}에게 닿는 디자인.",
  heroHeadlineStyle: { fontSize: 85, lineHeight: 1.2, letterSpacing: -0.03, fontWeight: 900, color: "#ffffff" },
  heroSubheadline: "광고대행사에서 {80여 개 이상}의 브랜드·클라이언트와 작업하며\n배너와 그래픽 디자인을 해온 {4년차 디자이너}입니다.",
  heroSubheadlineStyle: { fontSize: 22, lineHeight: 1.5, letterSpacing: -0.03, fontWeight: 500, color: "#aaaaaa" },
  mainIntroText: "여러 브랜드를 동시에 다루는 환경에서\n각 브랜드의 {정체성}을 유지하며 작업해왔고,\n소비자가 실제로 마주하는 화면을 기준으로\n{정보}와 {흐름}을 정리하는데 익숙합니다.",
  mainIntroTextStyle: { fontSize: 24, lineHeight: 1.35, letterSpacing: -0.03, fontWeight: 400, color: "#000000" },
  designProcessTitle: "DESIGN PROCESS",
  designProcessTitleStyle: { fontSize: 32, lineHeight: 1, letterSpacing: -0.03, fontWeight: 500, color: "rgba(255, 255, 255, 0.2)" },
  designProcessSteps: [
    { title: "브랜드 톤 설정", description: "브랜드에 맞는 톤과 분위기를 기준으로 디자인합니다." },
    { title: "정보 구조 정리", description: "정보가 한눈에 들어오도록 화면을 구성합니다." },
    { title: "매체 맞춤 디자인", description: "노출 환경을 고려해 결과물을 조정합니다" }
  ],
  designProcessStepTitleStyle: { fontSize: 20, lineHeight: 1.2, letterSpacing: -0.02, fontWeight: 900, color: "#ffffff" },
  designProcessStepDescriptionStyle: { fontSize: 14, lineHeight: 1.6, letterSpacing: 0, fontWeight: 500, color: "rgba(255, 255, 255, 0.5)" },
  worksGalleryTitle: "Selected Works",
  worksGalleryTitleStyle: { fontSize: 32, lineHeight: 1, letterSpacing: -0.03, fontWeight: 500, color: "rgba(255, 255, 255, 0.2)" },
  capabilitiesTitle: "그래픽과 영상, 커뮤니케이션 경험을 바탕으로\n브랜드를 이해하고 표현합니다.",
  capabilitiesTitleStyle: { fontSize: 31, lineHeight: 1.2, letterSpacing: -0.03, fontWeight: 500, color: "#ffffff" },
  capabilities: [
    { 
      title: 'Graphic Design', 
      description: '트렌드를 반영한 시각 언어와\n디테일한 완성도를 바탕으로\n브랜드의 메시지를 효과적으로 전달하는 그래픽 디자인' 
    },
    { 
      title: 'Video', 
      description: '그래픽 작업을 기반으로\n간단한 모션과 영상 편집을 활용한\n서브 영상 콘텐츠 제작' 
    },
    { 
      title: 'Communication', 
      description: '다수의 이해관계자와 협업하며\n기획 의도를 이해하고\n디자인 방향을 정리하는 커뮤니케이션' 
    },
    { 
      title: 'Brand Understanding', 
      description: '브랜드의 핵심 가치와 맥락을 이해하고\n소비자가 직관적으로 받아들일 수 있도록\n명확하게 시각화하는 디자인' 
    }
  ],
  capabilityItemTitleStyle: { fontSize: 22, lineHeight: 1.2, letterSpacing: -0.02, fontWeight: 900, color: "#ffffff" },
  capabilityItemDescriptionStyle: { fontSize: 18, lineHeight: 1.7, letterSpacing: -0.01, fontWeight: 500, color: "#cccccc" },
  aboutIntro: "{80여 개 이상}의 브랜드·클라이언트와 협업하며\n배너, 프로모션, 캠페인 그래픽을 중심으로\n다양한 업종의 커뮤니케이션 작업을 경험했습니다.",
  aboutIntroStyle: { fontSize: 28, lineHeight: 1.32, letterSpacing: -0.03, fontWeight: 500, color: "#ffffff" },
  aboutPerspectiveLabel: "Design Perspective",
  aboutDesignCriteria: "디자인을 할 때 형식보다 소비자의 이해 흐름을 먼저 봅니다.\n짧은 시간 안에 무엇이 전달되어야 하는지,\n어디서 선택이 이루어지는지를 기준으로 화면을 구성해왔습니다.",
  aboutWorkingStyleLabel: "Working Style",
  aboutWorkingStyle: "업무를 진행할 때 주어진 요청을 그대로 처리하기보다,\n목적과 사용 맥락을 먼저 확인하는 편입니다.\n필요하다면 방향을 제안하고, 더 나은 결과를 위해\n능동적으로 의견을 공유하며 작업해왔습니다.",
  aboutExperienceLabel: "Professional Experience",
  aboutExperience: "이전 회사에서는 디자인 업무와 함께 마케팅 커뮤니케이션 일부를 경험하며,\n성과 지표와 운영 흐름을 자연스럽게 이해하게 되었습니다.\n그 덕분에 디자인 결과물이 실제로 어떻게 사용되는지까지 고려하며\n작업할 수 있었습니다.",
  aboutClosing: "빠르게 소비되는 화면 속에서도\n소비자에게는 명확하고, 브랜드에는 무리가 없는 디자인을 지향합니다.",
  aboutClosingStyle: { fontSize: 24, lineHeight: 1.32, letterSpacing: -0.03, fontWeight: 500, color: "#ffffff" },
  aboutSectionSpacing: 120,
  bodyTextStyle: { fontSize: 18, lineHeight: 1.7, letterSpacing: -0.01, fontWeight: 500, color: "#cccccc" },
  pointColor: "#347BED",
  workTitleStyle: { fontSize: 120, lineHeight: 1, letterSpacing: -0.06, fontWeight: 900, color: "#ffffff" },
  sidebarStyle: { fontSize: 13, lineHeight: 1, letterSpacing: 0, fontWeight: 500, color: "#000000" },
  sectionHeadingStyle: { fontSize: 90, lineHeight: 1, letterSpacing: -0.05, fontWeight: 900, color: "#ffffff" },
  cardTitleStyle: { fontSize: 22, lineHeight: 1.2, letterSpacing: -0.02, fontWeight: 900, color: "#ffffff" },
  contactHeadline: "CONTACT",
  contactHeadlineStyle: { fontSize: 80, lineHeight: 1, letterSpacing: -0.03, fontWeight: 500, color: "#ffffff" },
  contactSubheadline: "그래픽 디자인 관련 제안을 환영합니다.\n포트폴리오 문의나 협업 제안도 편하게 연락 주세요.",
  contactSubheadlineStyle: { fontSize: 21, lineHeight: 1.33, letterSpacing: -0.03, fontWeight: 400, color: "rgba(255,255,255,0.4)" },
  workMetadataLabelStyle: { fontSize: 10, lineHeight: 1, letterSpacing: 0.15, fontWeight: 900, color: "#888888" },
  workMetadataValueStyle: { fontSize: 14, lineHeight: 1.2, letterSpacing: -0.01, fontWeight: 700, color: "#ffffff" },
  workOneLinerStyle: { fontSize: 20, lineHeight: 1.4, letterSpacing: -0.02, fontWeight: 500, color: "#aaaaaa" },
  workDetailHeaderBrandStyle: { fontSize: 90, lineHeight: 0.9, letterSpacing: -0.02, fontWeight: 900, color: "#ffffff" },
  workDetailHeaderTitleStyle: { fontSize: 28, lineHeight: 1.2, letterSpacing: -0.04, fontWeight: 800, color: "#ffffff" },
  workDetailHeaderBulletStyle: { fontSize: 16, lineHeight: 1.45, letterSpacing: -0.02, fontWeight: 500, color: "#cccccc" },
  workDetailTabStyle: { fontSize: 14, lineHeight: 1, letterSpacing: 0.1, fontWeight: 900, color: "#347bed" },
};

export const INITIAL_MENU: SidebarMenu = {
  main: "Main",
  about: "About",
  capability: "Capability",
  contact: "Contact"
};

export const INITIAL_WORKS: WorkItem[] = [
  {
    id: '1',
    brand: '게임',
    company: '아이템베이, DK모바일:리본',
    category: 'Game UI/UX & Art Direction',
    oneLiner: '사용자 경험을 극대화하는 게임 비주얼 디자인',
    thumbnail: 'https://i.imgur.com/J7hohW0.jpeg',
    role: '게임별 세계관과 유저 성향에 맞춘 프로모션 키비주얼 제작\n업데이트, 한정 이벤트, 혜택 강조형 배너 디자인\n빠른 정보 인지가 필요한 플랫폼 특성을 고려한\n카피 가독성과 CTA 중심의 구조 설계',
    media: ['In-game UI', 'Steam Page', 'Promotion Video', 'Social Media'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/J7hohW0.jpeg',
      'https://i.imgur.com/897HjNM.jpeg',
      'https://i.imgur.com/ktT7F25.jpeg',
      'https://i.imgur.com/jJsdp3e.jpeg',
      'https://i.imgur.com/jwuS7p1.jpeg',
      'https://i.imgur.com/f3TGjow.jpeg',
      'https://i.imgur.com/DkyqJWF.jpeg',
      'https://i.imgur.com/GRfeAfc.jpeg',
      'https://i.imgur.com/KXUXJe2.jpeg',
      'https://i.imgur.com/7WasRLJ.jpeg',
      'https://i.imgur.com/xjaZ3R3.jpeg',
      'https://i.imgur.com/l1TfsP3.jpeg'
    ]
  },
  {
    id: '11',
    brand: '인테리어',
    company: '룸앤홈, 클라르하임',
    category: '인테리어',
    oneLiner: '공간의 가치를 더하는 감각적인 라이프스타일 디자인',
    thumbnail: 'https://i.imgur.com/q7Ro9r1.jpeg',
    role: '공간 콘셉트와 제품 특성을 고려한 프로모션 비주얼 제작\n시즌·이벤트에 맞춘 톤앤무드 설계 및 이미지 보정\n이커머스 환경을 고려한 직관적인 레이아웃 구성',
    media: ['Interior', 'Lifestyle', 'Promotion', 'Video'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/IyGRIaT.mp4',
      'https://i.imgur.com/D70BYJr.jpeg',
      'https://i.imgur.com/q7Ro9r1.jpeg',
      'https://i.imgur.com/4sx9hjb.mp4',
      'https://i.imgur.com/DK8hOPJ.mp4',
      'https://i.imgur.com/Wcn7Z0F.jpeg',
      'https://i.imgur.com/tDssTti.jpeg',
      'https://i.imgur.com/XCpz1vO.jpeg',
      'https://i.imgur.com/TtsIlOL.png',
      'https://i.imgur.com/cyrfn0V.jpeg',
      'https://i.imgur.com/jmnm6j7.jpeg',
      'https://i.imgur.com/8k0hCOv.png',
      'https://i.imgur.com/tJFOYT1.jpeg',
      'https://i.imgur.com/Ml5OFjG.jpeg',
      'https://i.imgur.com/zHFkgng.jpeg',
      'https://i.imgur.com/jDRkzkn.jpeg',
      'https://i.imgur.com/PcJ0clT.jpeg',
      'https://i.imgur.com/B6P159Z.jpeg'
    ]
  },
  {
    id: '2',
    brand: '돈키호테',
    company: '돈키호테',
    category: 'Brand Identity & Promotion',
    oneLiner: '브랜드의 개성을 담아낸 온라인 프로모션 디자인',
    thumbnail: 'https://i.imgur.com/Nxn5Isj.jpeg',
    role: '브랜드 무드를 살린 SNS 콘텐츠 제작\n이벤트 목적에 맞춘 정보 구성과 레이아웃 설계\n한눈에 내용이 들어오는 화면 구성',
    media: ['Social Media', 'Web Banner', 'Promotion'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/Nxn5Isj.jpeg',
      'https://i.imgur.com/8ffHUWy.jpeg',
      'https://i.imgur.com/1hOtit7.jpeg',
      'https://i.imgur.com/6nkx6Fi.jpeg',
      'https://i.imgur.com/v7ITtYZ.jpeg',
      'https://i.imgur.com/YuM22NK.jpeg',
      'https://i.imgur.com/MWQn5Tu.jpeg',
      'https://i.imgur.com/xChQssM.jpeg',
      'https://i.imgur.com/5Z0bgUE.jpeg',
      'https://i.imgur.com/tkn8V0W.jpeg',
      'https://i.imgur.com/A2CFRVr.jpeg',
      'https://i.imgur.com/VIJ2jpV.jpeg',
      'https://i.imgur.com/n3YRrAg.jpeg',
      'https://i.imgur.com/LOQEoXM.jpeg',
      'https://i.imgur.com/jxTl421.jpeg'
    ]
  },
  {
    id: '3',
    brand: '패션',
    company: '에이세(현대홈쇼핑)',
    category: '패션',
    oneLiner: '트렌디한 감각과 실무 효율을 결합한 패션 이커머스 디자인',
    thumbnail: 'https://i.imgur.com/EhkviVl.jpeg',
    role: '브랜드 무드에 맞춘 패션 비주얼 제작\n플랫폼 특성을 고려한 상품 레이아웃 설계\n구매 전환을 고려한 프로모션 콘텐츠 구성',
    media: ['E-commerce', 'Lookbook', 'Social Media', 'Video'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/EhkviVl.jpeg',
      'https://i.imgur.com/Av5PPRJ.jpeg',
      'https://i.imgur.com/Vr2flcN.jpeg',
      'https://i.imgur.com/PT48Cp0.jpeg',
      'https://i.imgur.com/qbjoCR3.mp4',
      'https://i.imgur.com/8B5afL9.png',
      'https://i.imgur.com/BgD1FTo.jpeg',
      'https://i.imgur.com/O0teLVm.jpeg',
      'https://i.imgur.com/UiqExir.jpeg',
      'https://i.imgur.com/rqwbUJl.jpeg',
      'https://i.imgur.com/KErTEGA.jpeg',
      'https://i.imgur.com/Ihfullw.jpeg',
      'https://i.imgur.com/nYV72uv.jpeg',
      'https://i.imgur.com/GKPL9BL.jpeg',
      'https://i.imgur.com/IWRXfir.jpeg',
      'https://i.imgur.com/yEgZA0V.jpeg',
      'https://i.imgur.com/xed9lYV.jpeg',
      'https://i.imgur.com/koBcycu.mp4',
      'https://i.imgur.com/Vl96cyk.jpeg',
      'https://i.imgur.com/gTCCAxx.jpeg',
      'https://i.imgur.com/5wrDLa7.jpeg'
    ]
  },
  {
    id: '4',
    brand: '헬스',
    company: '큐링(snpe)',
    category: '헬스',
    oneLiner: '여성 타겟 헬스케어 비주얼 디자인',
    thumbnail: 'https://i.imgur.com/GpK4jYQ.jpeg',
    role: '뷰티 톤에 맞춘 헬스케어 콘텐츠 제작\n사용 상황이 바로 이해되는 상세·프로모션 구성\n효과 중심으로 정리한 그래픽 작업',
    media: ['Healthcare', 'Product Design', 'Education', 'Social Media'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/GpK4jYQ.jpeg',
      'https://i.imgur.com/5PhrsRb.jpeg',
      'https://i.imgur.com/JPC3b7N.jpeg',
      'https://i.imgur.com/J0pUr87.png',
      'https://i.imgur.com/4k7BFKv.jpeg',
      'https://i.imgur.com/iaBHfiv.jpeg',
      'https://i.imgur.com/AxFVTC.jpeg',
      'https://i.imgur.com/oqP7C0E.jpeg',
      'https://i.imgur.com/6Afjoim.jpeg',
      'https://i.imgur.com/WFIFgKd.jpeg',
      'https://i.imgur.com/YxVlES3.jpeg',
      'https://i.imgur.com/yJiXnFw.png',
      'https://i.imgur.com/4rOrTta.jpeg',
      'https://i.imgur.com/n2HK6a.jpeg',
      'https://i.imgur.com/6CIv8VS.jpeg'
    ]
  },
  {
    id: '5',
    brand: '뷰티',
    company: 'TS, 릴리이브',
    category: '뷰티',
    oneLiner: '브랜드 무드를 살린 뷰티 디자인',
    thumbnail: 'https://i.imgur.com/E2L4aBQ.jpeg',
    role: '브랜드 톤에 맞춰 캠페인 이미지와 프로모션 디자인 제작\n제품 장점이 바로 보이도록 상세 페이지와 배너 구성\n구매까지 흐름이 자연스럽게 이어지도록 화면 구성 정리',
    media: ['Beauty', 'Cosmetics', 'Social Media', 'Branding'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/E2L4aBQ.jpeg',
      'https://i.imgur.com/4nRIcwX.jpeg',
      'https://i.imgur.com/dIkHUIb.jpeg',
      'https://i.imgur.com/cANrvHq.jpeg',
      'https://i.imgur.com/6HCYTTx.jpeg',
      'https://i.imgur.com/vCbPjKT.jpeg',
      'https://i.imgur.com/fcU4o3m.jpeg',
      'https://i.imgur.com/y5IUqIx.jpeg',
      'https://i.imgur.com/jnA0AOQ.jpeg',
      'https://i.imgur.com/sMPt3tk.jpeg',
      'https://i.imgur.com/TzpG5rE.jpeg',
      'https://i.imgur.com/9wCa1zp.jpeg',
      'https://i.imgur.com/Sun1Cnu.jpeg',
      'https://i.imgur.com/tFvMckZ.jpeg',
      'https://i.imgur.com/6HLs7RB.jpeg',
      'https://i.imgur.com/6AXd5FK.jpeg',
      'https://i.imgur.com/tPtP2U5.jpeg',
      'https://i.imgur.com/hfiaudV.jpeg',
      'https://i.imgur.com/K4po9l9.jpeg',
      'https://i.imgur.com/xUVUJLP.jpeg',
      'https://i.imgur.com/hcPTn15.jpeg'
    ]
  },
  {
    id: '6',
    brand: '교육',
    company: '뇌새김, 세븐에듀, 스피킹맥스, 밀당PT, 에듀윌',
    category: '교육',
    oneLiner: '신뢰와 성과를 전하는 교육 브랜드 디자인',
    thumbnail: 'https://i.imgur.com/xmF3sNQ.jpeg',
    role: '학습 성과와 신뢰를 강조한 캠페인 디자인 제작\n복잡한 학습 정보를 쉽게 이해되도록 정리한 콘텐츠 구성\n플랫폼 특성에 맞춘 프로모션 그래픽 설계',
    media: ['Education', 'Promotion', 'Web Banner', 'Video'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/xmF3sNQ.jpeg',
      'https://i.imgur.com/CO5zUHL.jpeg',
      'https://i.imgur.com/QXObppQ.jpeg',
      'https://i.imgur.com/NUQRfAz.jpeg',
      'https://i.imgur.com/WGdZR5Y.jpeg',
      'https://i.imgur.com/706ENEc.jpeg',
      'https://i.imgur.com/h7Qe1CL.jpeg',
      'https://i.imgur.com/DrD9RJE.mp4',
      'https://i.imgur.com/uXJoqNv.jpeg'
    ]
  },
  {
    id: '7',
    brand: '식품',
    company: '헤이바디(현대홈쇼핑), 메디프레소, 미트박스',
    category: '식품',
    oneLiner: '브랜드의 맛과 신뢰를 전달하는 식품 콘텐츠 디자인',
    thumbnail: 'https://i.imgur.com/IMu82dF.jpeg',
    role: '제품 특성이 잘 드러나는 배너·프로모션 디자인 제작\n신선함과 신뢰감을 강조한 상세 페이지 구성\n다양한 식품 커머스 환경에 맞춘 콘텐츠 디자인 작업',
    media: ['Food & Beverage', 'E-commerce', 'Social Media', 'Banner Design'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/IMu82dF.jpeg',
      'https://i.imgur.com/oadcnhR.jpeg',
      'https://i.imgur.com/JsJvUra.jpeg',
      'https://i.imgur.com/CC5cBvE.jpeg',
      'https://i.imgur.com/3SZgve4.jpeg',
      'https://i.imgur.com/GVJwB95.jpeg',
      'https://i.imgur.com/DLG05dO.jpeg',
      'https://i.imgur.com/th35u1B.jpeg',
      'https://i.imgur.com/tPN5iwJ.jpeg',
      'https://i.imgur.com/7OCuLrQ.jpeg',
      'https://i.imgur.com/62PX0Em.jpeg',
      'https://i.imgur.com/g0R69sS.jpeg',
      'https://i.imgur.com/LmSjlzR.jpeg',
      'https://i.imgur.com/GDmsTWP.jpeg',
      'https://i.imgur.com/Ta98vCv.jpeg'
    ]
  },
  {
    id: '8',
    brand: '건강기능식품',
    company: '일양약품, 리턴큐, 먼슬리픽',
    category: '건강기능식품',
    oneLiner: '신뢰와 기능을 분명하게 전달하는 건강기능식품 디자인',
    thumbnail: 'https://i.imgur.com/bIhjwsw.jpeg',
    role: '중년 이상 타겟을 고려한 가독성 중심 프로모션 디자인 제작\n핵심 효능과 제품 특징이 바로 보이도록 정보 구성 정리\n구매 행동을 유도하는 배너·SNS 콘텐츠 디자인 작업',
    media: ['Health Functional Food', 'Promotion', 'Web Banner', 'SNS Content'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/bIhjwsw.jpeg',
      'https://i.imgur.com/QtLKgon.jpeg',
      'https://i.imgur.com/cXu4jR2.jpeg',
      'https://i.imgur.com/XicQDRB.jpeg',
      'https://i.imgur.com/V0HZPrg.jpeg',
      'https://i.imgur.com/4aBWyU8.jpeg',
      'https://i.imgur.com/jVqwRSF.jpeg',
      'https://i.imgur.com/GneciQS.jpeg',
      'https://i.imgur.com/IiPp7lC.jpeg'
    ]
  },
  {
    id: '9',
    brand: '반려동물',
    company: '럽마이펫, 울리',
    category: '반려동물',
    oneLiner: '반려동물과 일상을 함께하는 따뜻하고 직관적인 브랜드 디자인',
    thumbnail: 'https://i.imgur.com/ueYst19.jpeg',
    role: '반려동물 용품 특성을 고려한 친근한 프로모션 디자인 제작\n브랜드 톤을 살린 SNS 콘텐츠 및 간단한 영상 구성\n모델 컷과 제품 컷을 활용한 상세·커머스용 그래픽 작업',
    media: ['Pet Care', 'SNS Content', 'Promotion', 'Video'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/jM8kweq.mp4',
      'https://i.imgur.com/ueYst19.jpeg',
      'https://i.imgur.com/uzko5dj.jpeg',
      'https://i.imgur.com/jYlNT0t.mp4',
      'https://i.imgur.com/DLMltk3.jpeg',
      'https://i.imgur.com/ho1MTUT.jpeg',
      'https://i.imgur.com/1l36cTE.jpeg',
      'https://i.imgur.com/K953wPP.jpeg',
      'https://i.imgur.com/DuUPyqN.jpeg'
    ]
  },
  {
    id: '10',
    brand: '이벤트',
    company: '상시 이벤트, 할인 이벤트, 프로모션 캠페인',
    category: '이벤트',
    oneLiner: '참여를 이끄는 이벤트 디자인',
    thumbnail: 'https://i.imgur.com/Uotb8aB.jpeg',
    role: '할인·혜택이 한눈에 들어오는 이벤트 배너 제작\n즉각적인 반응을 유도하는 직관적인 메시지 구성\n채널 환경에 맞춰 주목도를 높인 프로모션 디자인 작업',
    media: ['Promotion', 'Sale Event', 'Web Banner', 'Marketing'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/Uotb8aB.jpeg',
      'https://i.imgur.com/1hwhpku.jpeg',
      'https://i.imgur.com/sqmgYaF.jpeg',
      'https://i.imgur.com/ZSPhYbD.jpeg',
      'https://i.imgur.com/qXjgUdu.jpeg',
      'https://i.imgur.com/J0iCWIQ.jpeg',
      'https://i.imgur.com/D8L4j1q.jpeg',
      'https://i.imgur.com/5fRUQro.jpeg',
      'https://i.imgur.com/6E7Bv2f.jpeg'
    ]
  },
  {
    id: '13',
    brand: '상세페이지',
    company: 'Promotion Landing Pages',
    category: '상세페이지',
    oneLiner: '주목을 이끄는 상세페이지 디자인',
    thumbnail: 'https://i.imgur.com/dY0Ukpo.jpeg',
    role: '첫 화면에서 관심을 끄는 정보 구성과 화면 배치 설계\n핵심 내용이 자연스럽게 읽히도록 정리한 콘텐츠 구성\n모바일 환경에 맞춘 가독성 중심 레이아웃 작업',
    media: ['Landing Page', 'Promotion', 'E-commerce'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/dY0Ukpo.jpeg',
      'https://i.imgur.com/z3Yu9O1.jpeg',
      'https://i.imgur.com/VHaCL2t.jpeg'
    ]
  },
  {
    id: '12',
    brand: 'etc',
    company: '한진관광, kb rise, 코닥, 에버블루, 보답',
    category: 'etc',
    oneLiner: '다양한 분야를 아우르는 그래픽 디자인',
    thumbnail: 'https://i.imgur.com/65PXATc.jpeg',
    role: '여행, 금융, 전자기기, 생활용품 등\n서로 다른 주제와 목적에 맞춰 그래픽 디자인 제작\n각 분야의 특성을 빠르게 파악해 메시지를 정리하고\n브랜드 톤에 맞춰 화면 구성과 디자인 완성',
    media: ['Branding', 'Graphic Design', 'Social Media', 'Marketing'],
    creativeDirections: [],
    visuals: [
      'https://i.imgur.com/65PXATc.jpeg',
      'https://i.imgur.com/hPGRLLx.jpeg',
      'https://i.imgur.com/BcR3xvX.jpeg',
      'https://i.imgur.com/WZqfD82.jpeg',
      'https://i.imgur.com/5iV0C2g.jpeg',
      'https://i.imgur.com/flrELtN.jpeg',
      'https://i.imgur.com/sJB0ZUk.jpeg',
      'https://i.imgur.com/q9xiRte.jpeg',
      'https://i.imgur.com/czJfhgC.jpeg',
      'https://i.imgur.com/4iElumt.jpeg',
      'https://i.imgur.com/nvh01AC.gif',
      'https://i.imgur.com/xQFohm1.jpeg',
      'https://i.imgur.com/hPiRbfA.jpeg',
      'https://i.imgur.com/uyWFCCI.jpeg',
      'https://i.imgur.com/CBxFPVU.jpeg',
      'https://i.imgur.com/4icmXQQ.jpeg',
      'https://i.imgur.com/JvC6El5.mp4',
      'https://i.imgur.com/LTpjwjp.jpeg',
      'https://i.imgur.com/8k7tGLW.mp4',
      'https://i.imgur.com/fAV7wCe.jpeg',
      'https://i.imgur.com/IfXeQcR.jpeg',
      'https://i.imgur.com/OGkC1Hj.jpeg',
      'https://i.imgur.com/b3Y5x1u.jpeg',
      'https://i.imgur.com/vXEK9kk.jpeg',
      'https://i.imgur.com/stMGVOf.jpeg',
      'https://i.imgur.com/aX8ra91.jpeg',
      'https://i.imgur.com/fn5Utj2.jpeg'
    ]
  }
];